[gutfit_servers]
gutfit-1 ansible_host=mtl.autho.cloud ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa
gutfit-2 ansible_host=your-secondary-server.com ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
